[package]
name = "day02"
version = "0.1.0"
authors = ["Matt Whelan <matt@blacklogik.com>"]
edition = "2018"

[dependencies]
regex = "1"
itertools = "0.9.0"
anyhow = "1.0.34"
thiserror = "1.0.22"
lazy_static = "1.4.0"
